export default[
    {
      providerName: "Agape Stores",
      ratePerHour: "N3000/hr",
      completedTasks: 80,
      positiveReviews: "100%",
      reliability: "80%",
      reviews: 35,
      stars: 4.5,
      category:["pharmacy","supermarket"],
      profileImg: "pharmacy.jpg", // Placeholder image link or URL for profile
    },
    {
      providerName: "Urban Movers",
      ratePerHour: "N3500/hr",
      completedTasks: 120,
      positiveReviews: "95%",
      reliability: "85%",
      reviews: 50,
      stars: 4.7,
      profileImg: "movers.jpg",
    },
    {
      providerName: "Quick Fix Plumbing",
      ratePerHour: "N4000/hr",
      completedTasks: 90,
      positiveReviews: "98%",
      reliability: "90%",
      reviews: 42,
      stars: 4.6,
      profileImg: "plumbing.jpg",
    },
    {
      providerName: "CleanPro Services",
      ratePerHour: "N2500/hr",
      completedTasks: 150,
      positiveReviews: "92%",
      reliability: "88%",
      reviews: 65,
      stars: 4.8,
      profileImg: "cleaning.jpg",
    },
    {
      providerName: "Super Groceries",
      ratePerHour: "N2000/hr",
      completedTasks: 200,
      positiveReviews: "100%",
      reliability: "95%",
      reviews: 80,
      stars: 4.9,
      profileImg: "groceries.jpg",
    },
    {
      providerName: "Best Furniture Assembly",
      ratePerHour: "N4500/hr",
      completedTasks: 60,
      positiveReviews: "97%",
      reliability: "85%",
      reviews: 30,
      stars: 4.4,
      profileImg: "furniture.jpg",
    },
    {
      providerName: "Tech Repairs",
      ratePerHour: "N5000/hr",
      completedTasks: 100,
      positiveReviews: "90%",
      reliability: "80%",
      reviews: 55,
      stars: 4.3,
      profileImg: "tech_repair.jpg",
    },
    {
      providerName: "Local Electricians",
      ratePerHour: "N4200/hr",
      completedTasks: 130,
      positiveReviews: "85%",
      reliability: "75%",
      reviews: 40,
      stars: 4.1,
      profileImg: "electrician.jpg",
    },
    {
      providerName: "AutoFix Mechanics",
      ratePerHour: "N3800/hr",
      completedTasks: 110,
      positiveReviews: "99%",
      reliability: "92%",
      reviews: 70,
      stars: 4.9,
      profileImg: "mechanic.jpg",
    },
    {
      providerName: "Landscaping Pros",
      ratePerHour: "N3300/hr",
      completedTasks: 140,
      positiveReviews: "93%",
      reliability: "89%",
      reviews: 75,
      stars: 4.7,
      profileImg: "landscaping.jpg",
    },
    {
      providerName: "Pest Control Plus",
      ratePerHour: "N2800/hr",
      completedTasks: 95,
      positiveReviews: "88%",
      reliability: "83%",
      reviews: 38,
      stars: 4.2,
      profileImg: "pest_control.jpg",
    },
    {
      providerName: "Professional Painters",
      ratePerHour: "N4500/hr",
      completedTasks: 85,
      positiveReviews: "94%",
      reliability: "86%",
      reviews: 48,
      stars: 4.6,
      profileImg: "painters.jpg",
    },
    {
      providerName: "Home Appliance Repairs",
      ratePerHour: "N4700/hr",
      completedTasks: 105,
      positiveReviews: "96%",
      reliability: "89%",
      reviews: 58,
      stars: 4.8,
      profileImg: "appliance_repair.jpg",
    },
    {
      providerName: "Elite Movers",
      ratePerHour: "N3400/hr",
      completedTasks: 170,
      positiveReviews: "91%",
      reliability: "87%",
      reviews: 72,
      stars: 4.5,
      profileImg: "elite_movers.jpg",
    },
    {
      providerName: "Window Cleaners",
      ratePerHour: "N2100/hr",
      completedTasks: 120,
      positiveReviews: "95%",
      reliability: "92%",
      reviews: 60,
      stars: 4.7,
      profileImg: "window_cleaners.jpg",
    },
    {
      providerName: "Reliable Carpenters",
      ratePerHour: "N5000/hr",
      completedTasks: 85,
      positiveReviews: "87%",
      reliability: "83%",
      reviews: 52,
      stars: 4.2,
      profileImg: "carpenter.jpg",
    },
    {
      providerName: "Event Caterers",
      ratePerHour: "N3000/hr",
      completedTasks: 160,
      positiveReviews: "99%",
      reliability: "93%",
      reviews: 68,
      stars: 4.8,
      profileImg: "catering.jpg",
    },
    {
      providerName: "Professional Bakers",
      ratePerHour: "N3800/hr",
      completedTasks: 180,
      positiveReviews: "100%",
      reliability: "95%",
      reviews: 85,
      stars: 5.0,
      profileImg: "bakers.jpg",
    },
    {
      providerName: "Tailor and Alterations",
      ratePerHour: "N2700/hr",
      completedTasks: 70,
      positiveReviews: "89%",
      reliability: "80%",
      reviews: 28,
      stars: 4.1,
      profileImg: "tailor.jpg",
    },
    {
      providerName: "Home Cleaning Experts",
      ratePerHour: "N2300/hr",
      completedTasks: 155,
      positiveReviews: "98%",
      reliability: "91%",
      reviews: 73,
      stars: 4.9,
      profileImg: "home_cleaning.jpg",
    }
  ];
  